pipeline:
  name: example
  identifier: example
  projectIdentifier: Demo_Sandbox
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        template:
          templateRef: new_stage_template_name
          versionLabel: "1"
