pipeline:
  name: storz-abc
  identifier: storz-abc
  projectIdentifier: Demo_Sandbox
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy
        identifier: Deploy
        template:
          templateRef: new_stage_template_name
